services:
    swibly-api:
        container_name: swibly-api
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
         - .env
        ports:
          - '$API_HOST:$API_PORT:8080'
        networks:
          - "swibly_internal"
          - "swibly_external"
        depends_on:
          - "postgres"
        restart: unless-stopped

    postgres:
        image: postgres:latest
        container_name: swibly-api-db
        environment:
            POSTGRES_DB: $POSTGRES_DATABASE
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        env_file:
          - .env
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        networks:
          - "swibly_internal"
        restart: unless-stopped

networks:
  swibly_internal:
    internal: true
  swibly_external:
