services:
    postgres:
        image: postgres:latest
        container_name: $DEBUG_POSTGRES_CONTAINER_NAME
        environment:
            POSTGRES_DB: $DEBUG_POSTGRES_DATABASE
            POSTGRES_USER: $DEBUG_POSTGRES_USER
            POSTGRES_PASSWORD: $DEBUG_POSTGRES_PASSWORD
        env_file:
          - .env
        ports:
            - '5432:5432'
        volumes:
            - ./pgdata:/var/lib/postgresql/data
