name: Deploy to Render
on:
  workflow_run:
    workflows:
      - Go Test
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-success: true
