name: Deploy to Render (Develop)
on:
  workflow_run:
    branches:
      - develop
    workflows:
      - Build and Push Docker Image (Develop)
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.DEV_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-success: true
